#!/bin/sh

# Create the vol and fa meshes
blockMesh
makeFaMesh

# create the initial time folder
cp -r 0_org 0

# get init files from simpleFoam case
pathSimpleCase=$(pwd)/initSimpleFoam
pathLatestTime=$pathSimpleCase/$(foamListTimes -case initSimpleFoam -latestTime)

cp $pathLatestTime/U 0/U
cp $pathLatestTime/k 0/k
cp $pathLatestTime/omega 0/omega
cp $pathLatestTime/p 0/p

# Run suspensionFoam
suspensionFoam > log
