#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

foamListTimes -rm -withZero

rm -r dynamicCode

foamCleanPolyMesh

#------------------------------------------------------------------------------
