#!/bin/sh

# create vol mesh
blockMesh

# create cone geometry
python makeInitialCone.py

# create fa mesh
makeFaMesh

# create the intial time folder
cp -r 0_org 0

# Run suspensionFoam
suspensionFoam > log


