#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------
set -x

wclean libso settlingModels
wclean libso sedbedManager
wclean libso faMeshProjection

#------------------------------------------------------------------------------
